# NumPy

In [2]:
import numpy as np

In [3]:
np.__version__

'1.23.5'

In [2]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [3]:
arr = np.array( [[ 1, 2, 3],[ 4, 2, 5]] ) 

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.ndim

2

In [6]:
arr.shape

(2, 3)

In [16]:
arr.size

6

In [8]:
arr.dtype

dtype('int32')

In [10]:
b=np.array([1,2,3,4,5],complex)

In [11]:
b

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [12]:
b.itemsize

16

In [13]:
b.size

5

In [17]:
arr.itemsize

4

In [18]:
b.dtype

dtype('complex128')

In [6]:
l1=[1,2,3,4]
type(l1)

list

In [7]:
a1=np.array(l1)
type(a1)

numpy.ndarray

In [8]:
b1=np.asarray(l1)
type(b1)

numpy.ndarray

In [9]:
x = np.empty([3,2], dtype = int)


In [10]:
x

array([[-1926424096,         547],
       [-1905323776,         547],
       [          0, -2147483648]])

# arange function

In [21]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
np.arange(30,20)

array([], dtype=int32)

In [24]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [25]:
np.arange(-30,20) 

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

# Zeros()

In [26]:
print(np.zeros(6))

[0. 0. 0. 0. 0. 0.]


In [27]:
print(np.zeros((6,), dtype=int))

[0 0 0 0 0 0]


In [28]:
print(np.zeros((6,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [29]:
s1=(3,2)  
print(np.zeros(s1)) 

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [31]:
np.zeros((3,), dtype=[('x', 'i4'), ('y', 'i4')])

array([(0, 0), (0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

# Ones()

In [3]:
np.ones((2,6)) 

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [4]:
np.ones([2, 2], dtype = int)

array([[1, 1],
       [1, 1]])

# randint()

In [5]:
np.random.randint(10,30) 

12

In [6]:
np.random.randint(1) 

0

In [7]:
np.random.randint(1,3,5) 

array([1, 2, 1, 2, 1])

In [8]:
np.random.randint(10,20,(4,5))

array([[16, 19, 15, 17, 19],
       [14, 16, 11, 10, 19],
       [16, 17, 14, 14, 15],
       [15, 16, 11, 11, 18]])

In [9]:
np.random.randint(10,20,(5,4))

array([[11, 19, 10, 18],
       [18, 10, 15, 16],
       [15, 14, 10, 10],
       [15, 14, 18, 10],
       [17, 10, 12, 13]])

In [10]:
np.random.randint(low = 0, high = 3, size = 5) 

array([1, 0, 0, 2, 0])

In [11]:
np.random.randint(low = 4, size =(2, 3))

array([[3, 0, 3],
       [0, 2, 0]])

In [12]:
np.random.randint(2, 10, (2, 3, 4)) 

array([[[2, 4, 2, 9],
        [6, 4, 6, 5],
        [2, 9, 6, 4]],

       [[8, 4, 9, 3],
        [3, 8, 6, 5],
        [2, 9, 8, 2]]])

# Numpy operations

In [14]:
arr1 = np.arange(4, dtype = np.float_).reshape(2, 2) 
 
print('First array:') 
print(arr1)
 
print('\nSecond array:') 
arr2 = np.array([11, 12]) 
print(arr2)
 
print('\nAdding the two arrays:') 
print(np.add(arr1, arr2))
 
print('\nSubtracting the two arrays:') 
print(np.subtract(arr1, arr2))
 
print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))
 
print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))

First array:
[[0. 1.]
 [2. 3.]]

Second array:
[11 12]

Adding the two arrays:
[[11. 13.]
 [13. 15.]]

Subtracting the two arrays:
[[-11. -11.]
 [ -9.  -9.]]

Multiplying the two arrays:
[[ 0. 12.]
 [22. 36.]]

Dividing the two arrays:
[[0.         0.08333333]
 [0.18181818 0.25      ]]


# reciprocal()

In [15]:
arr = np.array([25, 1.33, 1, 1, 100]) 
 
print('Our array is:')
print(arr)
 
print('\nAfter applying reciprocal function:') 
print(np.reciprocal(arr))
 
arr2 = np.array([25], dtype = int)
print('\nThe second array is:')
print(arr2)
 
print('\nAfter applying reciprocal function:') 
print(np.reciprocal(arr2))

Our array is:
[ 25.     1.33   1.     1.   100.  ]

After applying reciprocal function:
[0.04      0.7518797 1.        1.        0.01     ]

The second array is:
[25]

After applying reciprocal function:
[0]


# power()

In [16]:
arr = np.array([5, 10, 15]) 
 
print('First array is:') 
print(arr)
 
print('\nApplying power function:') 
print(np.power(arr, 2))
 
print('\nSecond array is:') 
arr1 = np.array([1, 2, 3]) 
print(arr1)
 
print('\nApplying power function again:') 
print(np.power(arr, arr1))

First array is:
[ 5 10 15]

Applying power function:
[ 25 100 225]

Second array is:
[1 2 3]

Applying power function again:
[   5  100 3375]


# mod()

In [17]:
arr = np.array([5, 15, 20]) 
arr1 = np.array([2, 5, 9]) 
 
print('First array:') 
print(arr) 
 
print('\nSecond array:') 
print(arr1)
 
print('\nApplying mod() function:') 
print(np.mod(arr, arr1))
 
print('\nApplying remainder() function:') 
print(np.remainder(arr, arr1))

First array:
[ 5 15 20]

Second array:
[2 5 9]

Applying mod() function:
[1 0 2]

Applying remainder() function:
[1 0 2]


# max()

In [18]:
array1 = np.array([10, 12, 14, 11, 5])

# return the largest element 
maxValue= np.max(array1)

print(maxValue)

14


# Array Indexing and slicing

In [11]:
ai = np.arange(10) 
sl = slice(2,7,2)
ai[sl]

array([2, 4, 6])

In [15]:
data = np.array([1, 2, 3])
data[1]

2

In [15]:
print(data[1:])

[2 3]


In [16]:
print(data[-1:])

[3]


In [19]:
a2 = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a2 < 5)

[[ True  True  True  True]
 [False False False False]
 [False False False False]]


In [20]:
print(a2[a2<5])

[1 2 3 4]


In [3]:
mat = np.arange(0,100).reshape(10,10) 

In [4]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
row = 4
col = 5

In [6]:
mat[row,col] 

45

In [7]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [6]:
mat[:,col] 

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [8]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
mat[2:6,2:4,]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [7]:
mat[1:2,2:4,]

array([[12, 13]])

In [8]:
mat[2:3,2:3]

array([[22]])

In [9]:
mat[3:5,2:4,]

array([[32, 33],
       [42, 43]])

In [10]:
mat[2:3,4:5,]

array([[24]])

In [4]:
import pandas as pd
fp='C:\\Users\\dhyan\\Downloads\\EmployeeSampleData\\esd.xlsx'
df=pd.read_excel(fp)
df

EEID        Full Name                 Job Title  Department  \
0    E02387      Emily Davis                Sr. Manger          IT   
1    E04105    Theodore Dinh       Technical Architect          IT   
2    E02572     Luna Sanders                  Director     Finance   
3    E02832  Penelope Jordan  Computer Systems Manager          IT   
4    E01639        Austin Vo               Sr. Analyst     Finance   
..      ...              ...                       ...         ...   
995  E03094     Wesley Young               Sr. Analyst   Marketing   
996  E01909     Lillian Khan                   Analyst     Finance   
997  E04398      Oliver Yang                  Director   Marketing   
998  E02521      Lily Nguyen               Sr. Analyst     Finance   
999  E03545      Sofia Cheng            Vice President  Accounting   

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604   
1             Manufacturing    Male      Asian   59 1997-11-29          99975   
2       Speciality Products  Female  Caucasian   50 2006-10-26         163099   
3             Manufacturing  Female  Caucasian   26 2019-09-27          84913   
4             Manufacturing    Male      Asian   55 1995-11-20          95409   
..                      ...     ...        ...  ...        ...            ...   
995     Speciality Products    Male  Caucasian   33 2016-09-18          98427   
996     Speciality Products  Female      Asian   44 2010-05-31          47387   
997     Speciality Products    Male      Asian   31 2019-06-10         176710   
998     Speciality Products  Female      Asian   33 2012-01-28          95960   
999               Corporate  Female      Asian   63 2020-07-26         216195   

     Bonus %        Country       City  Exit Date  
0       0.15  United States    Seattle 2021-10-16  
1       0.00          China  Chongqing        NaT  
2       0.20  United States    Chicago        NaT  
3       0.07  United States    Chicago        NaT  
4       0.00  United States    Phoenix        NaT  
..       ...            ...        ...        ...  
995     0.00  United States   Columbus        NaT  
996     0.00          China    Chengdu 2018-01-08  
997     0.15  United States      Miami        NaT  
998     0.00          China    Chengdu        NaT  
999     0.31  United States      Miami        NaT  

[1000 rows x 14 columns]

In [6]:
pp='E:\\PUBG_V2.8.0_Cleaned.csv'
pubg=pd.read_csv(pp)
pubg

userName  \
0      Hafiz Owais Rafique Sialvi   
1                     Iqrabzu Bzu   
2                   Imran Malaung   
3                 Muhammad Saleem   
4                Md faisal Ahamed   
...                           ...   
19762                  Rana Hamza   
19763                PIANO GAMING   
19764                  Ram Shrest   
19765         Anjonavo syam Piyal   
19766                Sachin Thapa   

                                                 content  score  \
0      Im playing since season 8 It was awesome but t...      3   
1                                              Nice game      3   
2                                      Please new update      1   
3                                             Excellent       5   
4                                        I love tha game      5   
...                                                  ...    ...   
19762                     I have dnot receved new update      5   
19763                                            Perfect      5   
19764                                                Ral      5   
19765                                     Simply Amazing      5   
19766                                 I need m4 glacier       5   

                        at appVersion  
0      2023-11-01 01:06:37      2.8.0  
1      2023-11-02 16:12:37      2.8.0  
2      2023-11-02 10:48:33      2.8.0  
3      2023-10-30 02:05:22      2.8.0  
4      2023-10-30 06:00:24      2.8.0  
...                    ...        ...  
19762  2023-11-09 00:36:05      2.8.0  
19763  2023-11-09 01:38:30      2.8.0  
19764  2023-11-08 17:14:21      2.8.0  
19765  2023-11-06 02:44:38      2.8.0  
19766  2023-11-08 17:08:48      2.8.0  

[19767 rows x 5 columns]

# Masking

In [11]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [12]:
mat[mat<50] 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [13]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [14]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])